apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: inventory-tls
  labels:
    app: inventory
  name: inventory
spec:
  ports:
  - name: inventory-proxy
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: inventory
  type: ClusterIP
